### ISSUE TITLE
running coverlovin2 with pytests fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/coverlovin2#1]
Running `coverlovin2 --test-only -se .` within the coverlovin2 project directory results in

```
INFO: [MainThread coverlovin2]: Album details found: \uff5b "my artist" ¦ "my album" \uff5d within file "coverlovin2\coverlovin2\test\test_resources\ARTIST ALBUM.flac"
Traceback (most recent call last):
  File "C:\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\.virtualenvs\coverlovin2-rAPKj25Z\Scripts\coverlovin2.exe\__main__.py", line 9, in <module>
  File "c:\users\user1\.virtualenvs\coverlovin2-rapkj25z\scripts\coverlovin2.py", line 1832, in main
    print(msg)
  File "c:\users\user1\.virtualenvs\coverlovin2-rapkj25z\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uff5b' in position 28: character maps to <undefined>
```

Using Windows 10 within MinGW Bash, `$BASH_VERSION` `4.4.23(1)-release`, Python 3.7.1.

Running locale testing (taken from this [SO A](https://stackoverflow.com/questions/54625182/what-is-the-list-of-python-settings-that-affect-encoding-decoding-and-printing/54625183#54625183))
```Python
import os, sys, locale

print('environment:')
print('-E (ignore PYTHON* environment variables) ? %s' %
      (True if sys.flags.ignore_environment else False))
for env in ('LC_ALL', 'LANG', 'LC_CTYPE',
            'LANGUAGE', 'PYTHONIOENCODING',
            'PYTHONLEGACYWINDOWSSTDIO'):
    if env in os.environ:
        print('"%s"="%s"' % (env, os.environ[env]))
    else:
        print('"%s" not set' % env)

print()
print('sys module:')
print('getdefaultencoding "%s"' % sys.getdefaultencoding())
print('sys.stdin.encoding "%s"' % sys.stdin.encoding)
print('sys.stdout.encoding "%s"' % sys.stdout.encoding)
print('sys.stderr.encoding "%s"' % sys.stderr.encoding)

print()
print('locale:')
try:
    getattr(locale,'nl_langinfo')
    print('locale.nl_langinfo(locale.CODESET) "%s"' \
          % locale.nl_langinfo(locale.CODESET))
except AttributeError:
    print('locale.nl_langinfo not available')
print('locale.getdefaultlocale()[1] "%s"' \
      % locale.getdefaultlocale()[1])
print('locale.getpreferredencoding() "%s"' \
      % locale.getpreferredencoding())
```

results in
```
environment:
-E (ignore PYTHON* environment variables) ? False
"LC_ALL" not set
"LANG"="en_US.UTF-8"
"LC_CTYPE" not set
"LANGUAGE" not set
"PYTHONIOENCODING" not set
"PYTHONLEGACYWINDOWSSTDIO" not set

sys module:
getdefaultencoding "utf-8"
sys.stdin.encoding "cp1252"
sys.stdout.encoding "cp1252"
sys.stderr.encoding "cp1252"

locale:
locale.nl_langinfo not available
locale.getdefaultlocale()[1] "cp1252"
locale.getpreferredencoding() "cp1252"
```

**Comment by jtmoon79** [comment]
FIxed in latest run of pytests.  https://travis-ci.com/jtmoon79/coverlovin2/jobs/180859159
