### ISSUE TITLE
Travis 3.9 build fails; ModuleNotFoundError: No module named 'exceptiongroup'

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/coverlovin2#23]
Travis build for Python 3.9.15 [fails to run pytest](https://app.travis-ci.com/github/jtmoon79/coverlovin2/jobs/590828417) due to `ModuleNotFoundError: No module named 'exceptiongroup'`.

```text
$ ./tools/pytest-run.sh --cov=./coverlovin2/ --cov-config=./.coveragerc --cov-report=xml --log-cli-level=DEBUG --verbosity=1
+exec python -m pytest -vv --full-trace --showlocals --cov-config=./.coveragerc --cov-report=xml --cov=./coverlovin2/ --cov-config=./.coveragerc --cov-report=xml --log-cli-level=DEBUG --verbosity=1 ./coverlovin2/
Traceback (most recent call last):
  File "/opt/python/3.9.15/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/python/3.9.15/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/python/3.9.15/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/_pytest/_code/code.py", line 60, in <module>
    from exceptiongroup import BaseExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
The command "./tools/pytest-run.sh --cov=./coverlovin2/ --cov-config=./.coveragerc --cov-report=xml --log-cli-level=DEBUG --verbosity=1" exited with 1.
```

This only affects Python 3.9. Python versions 3.8, 3.10, 3.11 [succeed](https://app.travis-ci.com/github/jtmoon79/coverlovin2/builds/258718723) in the same Travis build run [and Travis configuration](https://github.com/jtmoon79/coverlovin2/blob/9f028496d8a6273dfc8f6a2fe3516e17cfd6578b/.travis.yml).

The prior dump of `pip list` shows (missing `exceptiongroup`)

```text
$ pip list -vvv
Package            Version    Location                                                         Installer
------------------ ---------- ---------------------------------------------------------------- ---------
attrs              22.1.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
autocommand        2.2.2      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
bleach             5.0.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
certifi            2022.12.7  /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
cffi               1.15.1     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
charset-normalizer 2.1.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
codecov            2.1.12     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
commonmark         0.9.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
coverage           6.5.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
coveralls          3.3.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
cryptography       38.0.4     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
dataclasses        0.6        /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
distlib            0.3.6      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
docopt             0.6.2      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
docutils           0.19       /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
filelock           3.8.2      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
idna               3.4        /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
importlib-metadata 5.1.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
iniconfig          1.1.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
jaraco.classes     3.2.3      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
jeepney            0.8.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
keyring            23.11.0    /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
mock               4.0.3      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
more-itertools     9.0.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
musicbrainzngs     0.7.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
mutagen            1.46.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
mypy               0.991      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
mypy-extensions    0.4.3      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
nose               1.3.7      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
numpy              1.23.4     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
packaging          22.0       /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
path               16.6.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pathspec           0.10.3     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
Pillow             9.3.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pip                22.3.1     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pip-run            9.0.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pipenv             2022.11.30 /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pkginfo            1.9.2      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
platformdirs       2.6.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pluggy             1.0.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
py                 1.11.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pycparser          2.21       /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
Pygments           2.13.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pyparsing          3.0.9      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pytest             7.2.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pytest-cov         4.0.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
pytest-dependency  0.5.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
PyYAML             6.0        /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
readme-renderer    37.3       /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
requests           2.28.1     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
requests-toolbelt  0.10.1     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
rfc3986            2.0.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
rich               12.6.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
SecretStorage      3.3.3      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
setuptools         65.6.3     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
six                1.16.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
tabulate           0.9.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
tomli              2.0.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
twine              4.0.2      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
typing_extensions  4.4.0      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
urllib3            1.26.13    /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
virtualenv         20.17.1    /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
virtualenv-clone   0.5.7      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
webencodings       0.5.1      /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
wheel              0.38.4     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
yamllint           1.28.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
zipp               3.11.0     /home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages pip
```

Whereas, `pip list` on Travis Python 3.8.13 build has `exceptiongroup`

```text
Package            Version    Location                                                         Installer
------------------ ---------- ---------------------------------------------------------------- ---------
attrs              22.1.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
autocommand        2.2.2      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
bleach             5.0.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
certifi            2022.12.7  /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
cffi               1.15.1     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
charset-normalizer 2.1.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
codecov            2.1.12     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
commonmark         0.9.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
coverage           6.5.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
coveralls          3.3.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
cryptography       38.0.4     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
dataclasses        0.6        /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
distlib            0.3.6      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
docopt             0.6.2      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
docutils           0.19       /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
exceptiongroup     1.0.4      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
filelock           3.8.2      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
idna               3.4        /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
importlib-metadata 5.1.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
iniconfig          1.1.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
jaraco.classes     3.2.3      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
jeepney            0.8.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
keyring            23.11.0    /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
mock               4.0.3      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
more-itertools     9.0.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
musicbrainzngs     0.7.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
mutagen            1.46.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
mypy               0.991      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
mypy-extensions    0.4.3      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
nose               1.3.7      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
numpy              1.23.1     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
packaging          22.0       /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
path               16.6.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pathspec           0.10.3     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
Pillow             9.3.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pip                22.3.1     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pip-run            9.0.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pipenv             2022.11.30 /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pkginfo            1.9.2      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
platformdirs       2.6.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pluggy             1.0.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
py                 1.11.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pycparser          2.21       /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
Pygments           2.13.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pyparsing          3.0.9      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pytest             7.2.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pytest-cov         4.0.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
pytest-dependency  0.5.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
PyYAML             6.0        /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
readme-renderer    37.3       /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
requests           2.28.1     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
requests-toolbelt  0.10.1     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
rfc3986            2.0.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
rich               12.6.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
SecretStorage      3.3.3      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
setuptools         65.6.3     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
six                1.16.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
tabulate           0.9.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
tomli              2.0.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
twine              4.0.2      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
typing_extensions  4.4.0      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
urllib3            1.26.13    /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
virtualenv         20.17.1    /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
virtualenv-clone   0.5.7      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
webencodings       0.5.1      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
wheel              0.38.4     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
yamllint           1.28.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
zipp               3.11.0     /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages pip
```

Running `git grep exceptiongroup` does not have matches (so package `exceptiongroup` isn't specified within the project).

Looking at [pytest project `setup.cfg`](https://github.com/pytest-dev/pytest/blob/7.2.0/setup.cfg#L51) there is no obvious reason `exceptiongroup` fails to install.

**Comment by jtmoon79** [comment]
A quick test install `pytest` within docker images for `python:3.8` and `python:3.9` failed to elicit the exception (`exceptiongroup` was installed for the different python versions).

```text
docker run python:3.9 bash -c 'set -x; pip install pytest && pip list -vv'
```

So the problem is not within a `pytest` project dependency.
