### ISSUE TITLE
Circle CI `test_pytest` fails; ModuleNotFoundError: pluggy

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/coverlovin2#29]
During Circle CI job `test_pytest`, during the `run` step, is script code:

```
      - run:
          name: test coverlovin2 pytests
          command: |
            set -eux
            pwd
            SHELL_ENV=.shell-env
            source "${SHELL_ENV}"
            "${PIPENV}" run pip list -v
            "${PIPENV}" run pytest -v ./coverlovin2/test
```

The call to `"${PIPENV}" run pytest -v ./coverlovin2/test` fails with

```
+ /home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pipenv run pytest -v ./coverlovin2/test
Traceback (most recent call last):
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/_pytest/_code/code.py", line 35, in <module>
    import pluggy
ModuleNotFoundError: No module named 'pluggy'

Exited with code exit status 1
```

Oddly, `pluggy` was added to `Pipfile` should be installed (as of 177417d91d016259ab6f4d7e4dcfdd504605ded6).

The full output looks like:
```
+ pwd
/home/circleci/project
+ SHELL_ENV=.shell-env
+ source .shell-env
++ export PIPENV_CACHE_DIR=/home/circleci/.pipenv-cache
++ PIPENV_CACHE_DIR=/home/circleci/.pipenv-cache
++ export PIPENV_VIRTUALENV=/home/circleci/.pipenv-venv
++ PIPENV_VIRTUALENV=/home/circleci/.pipenv-venv
++ export WORKON_HOME=/home/circleci/.pipenv-venv
++ WORKON_HOME=/home/circleci/.pipenv-venv
++ export PIPENV=/home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pipenv
++ PIPENV=/home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pipenv
+ /home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pipenv run pip list -v
Package            Version   Location                                                                 Installer
------------------ --------- ------------------------------------------------------------------------ ---------
attrs              23.1.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
autocommand        2.2.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
certifi            2023.7.22 /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
charset-normalizer 3.3.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
codecov            2.1.13    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
coverage           6.5.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
coveralls          3.3.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
cryptography       41.0.5    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
distlib            0.3.7     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
docopt             0.6.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
docutils           0.20.1    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
exceptiongroup     1.1.3     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
filelock           3.12.2    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
idna               3.4       /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
importlib-metadata 6.7.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
iniconfig          2.0.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
jaraco.context     4.3.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
jaraco.env         1.0.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
jaraco.text        3.11.1    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
jeepney            0.8.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
mdurl              0.1.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
musicbrainzngs     0.7.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
mutagen            1.47.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
mypy-extensions    1.0.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
nh3                0.2.14    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
packaging          23.2      /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pathspec           0.11.2    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pip                23.3.1    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pipenv             2023.10.3 /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pkginfo            1.9.6     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
platformdirs       3.11.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pycparser          2.21      /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pydantic           2.4.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pydantic_core      2.10.1    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
Pygments           2.16.1    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pytest             7.4.3     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pytest-cov         4.1.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
pytest-dependency  0.5.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
PyYAML             6.0.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
requests           2.31.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
requests-toolbelt  1.0.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
rfc3986            2.0.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
rich               13.6.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
SecretStorage      3.3.3     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
setuptools         68.0.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
tabulate           0.9.0     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
tomli              2.0.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
twine              4.0.2     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
typing_extensions  4.7.1     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
urllib3            2.0.7     /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
virtualenv         20.24.6   /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
wheel              0.41.3    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
yamllint           1.32.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
zipp               3.15.0    /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages pip
+ /home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pipenv run pytest -v ./coverlovin2/test
Traceback (most recent call last):
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages/_pytest/_code/code.py", line 35, in <module>
    import pluggy
ModuleNotFoundError: No module named 'pluggy'

Exited with code exit status 1
```

**Comment by jtmoon79** [comment]
The previous job `prep_workspace_cache` the creates the pipenv environment has these logs

```
...
+ pipenv install --dev
Creating a virtualenv for this project...
Pipfile: /home/circleci/project/Pipfile
Using /home/circleci/.pyenv/versions/3.7.17/bin/python3.7m (3.7.17) to create virtualenv...
created virtual environment CPython3.7.17.final.0-64 in 897ms
  creator CPython3Posix(dest=/home/circleci/.pipenv-venv/project-zxI9dQ-Q, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/circleci/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!

Virtualenv location: /home/circleci/.pipenv-venv/project-zxI9dQ-Q
Installing dependencies from Pipfile.lock (2daa17)...
Installing dependencies from Pipfile.lock (2daa17)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
+ pipenv run pip install --upgrade pipenv
Collecting pipenv
  Downloading pipenv-2023.10.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: certifi in /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages (from pipenv) (2023.7.22)
Requirement already satisfied: setuptools>=67 in /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages (from pipenv) (67.7.2)
Requirement already satisfied: virtualenv>=20.24.2 in /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages (from pipenv) (20.24.6)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages (from virtualenv>=20.24.2->pipenv) (0.3.7)
Collecting filelock<4,>=3.12.2 (from virtualenv>=20.24.2->pipenv)
  Downloading filelock-3.12.2-py3-none-any.whl.metadata (2.7 kB)
Collecting importlib-metadata>=6.6 (from virtualenv>=20.24.2->pipenv)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: platformdirs<4,>=3.9.1 in /home/circleci/.pipenv-venv/project-zxI9dQ-Q/lib/python3.7/site-packages (from virtualenv>=20.24.2->pipenv) (3.11.0)
Collecting zipp>=0.5 (from importlib-metadata>=6.6->virtualenv>=20.24.2->pipenv)
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting typing-extensions>=3.6.4 (from importlib-metadata>=6.6->virtualenv>=20.24.2->pipenv)
  Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Downloading pipenv-2023.10.3-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 67.7 MB/s eta 0:00:00

Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: zipp, typing-extensions, filelock, importlib-metadata, pipenv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic 2.4.2 requires annotated-types>=0.4.0, which is not installed.
pytest 7.4.3 requires pluggy<2.0,>=0.12, which is not installed.
rich 13.6.0 requires markdown-it-py>=2.2.0, which is not installed.
twine 4.0.2 requires keyring>=15.1, which is not installed.
twine 4.0.2 requires readme-renderer>=35.0, which is not installed.
Successfully installed filelock-3.12.2 importlib-metadata-6.7.0 pipenv-2023.10.3 typing-extensions-4.7.1 zipp-3.15.0
```

I guess there is a known errant behavior in `pip` or `pipenv`. I'm not sure what I can do about that. The only option I can think of is "brute force install" the necessary modules... but how?
