### ISSUE TITLE
Script fails with KeyError: 'JPG'

### ISSUE THREAD

**Issue by ckotte** [jtmoon79/coverlovin2#6]
```
coverlovin2 -s- ~/Music
[...]
ERROR: [Thread-5 coverlovin2]: 'JPG'
Traceback (most recent call last):
  File "/usr/bin/coverlovin2.py", line 1731, in search_create_image
    res = is_.go()
  File "/usr/bin/coverlovin2.py", line 1036, in go
    return self.write_album_image()
  File "/usr/bin/coverlovin2.py", line 1113, in write_album_image
    self._image.save(self.copy_dst, self.image_type.value.upper())
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2140, in save
    save_handler = SAVE[format.upper()]
KeyError: 'JPG'
ERROR: [Thread-3 coverlovin2]: 'JPG'
Traceback (most recent call last):
  File "/usr/bin/coverlovin2.py", line 1731, in search_create_image
    res = is_.go()
  File "/usr/bin/coverlovin2.py", line 1036, in go
    return self.write_album_image()
  File "/usr/bin/coverlovin2.py", line 1113, in write_album_image
    self._image.save(self.copy_dst, self.image_type.value.upper())
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2140, in save
    save_handler = SAVE[format.upper()]
KeyError: 'JPG'
```

The script doesn't stop. It hangs "forever". I have to press CTRL-C to abort the script. It also doesn't finish when using ```--test```

This error is added when I press CTRL-C:
```
^CTraceback (most recent call last):
  File "/usr/bin/coverlovin2", line 8, in <module>
    sys.exit(main())
  File "/usr/bin/coverlovin2.py", line 2087, in main
    task_queue.join()
  File "/usr/lib/python3.8/queue.py", line 89, in join
    self.all_tasks_done.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

```

**Comment by jtmoon79** [comment]
@ckotte hopefully this fixed the problem you ran into.
